# Generated by Django 4.2.11 on 2024-04-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Currency',
        ),
    ]
